export const feedUrls: Record<string, string> = {
  digitec: "https://static.digitecgalaxus.ch/feeds/rss/digitec_CH_de.xml",
  galaxus: "https://static.digitecgalaxus.ch/feeds/rss/Galaxus_CH_de.xml",
  "srf-latest": "https://www.srf.ch/news/bnf/rss/19032223",
  "srf-switzerland": "https://www.srf.ch/news/bnf/rss/1890",
  "srf-international": "https://www.srf.ch/news/bnf/rss/1922",
  "srf-economy": "https://www.srf.ch/news/bnf/rss/1926",
  "srf-sport": "https://www.srf.ch/sport/bnf/rss/718",
  "srf-football": "https://www.srf.ch/sport/bnf/rss/2562",
  "srf-culture": "https://www.srf.ch/kultur/bnf/rss/454",
  "srf-news": "https://www.srf.ch/news/bnf/rss/1646",
  "srf-ice-hockey": "https://www.srf.ch/sport/bnf/rss/3418",
  "srf-tennis": "https://www.srf.ch/sport/bnf/rss/2814",
  "srf-ski": "https://www.srf.ch/sport/bnf/rss/787950",
  "srf-athletics": "https://www.srf.ch/sport/bnf/rss/3042",
  "srf-motorsport": "https://www.srf.ch/sport/bnf/rss/2958",
  "srf-more-sport": "https://www.srf.ch/sport/bnf/rss/3010",
  "srf-film": "https://www.srf.ch/kultur/bnf/rss/8726",
  "srf-society": "https://www.srf.ch/kultur/bnf/rss/8798",
  "srf-literature": "https://www.srf.ch/kultur/bnf/rss/8762",
  "srf-music": "https://www.srf.ch/kultur/bnf/rss/8738",
  "srf-art": "https://www.srf.ch/kultur/bnf/rss/8774",
  "srf-theater": "https://www.srf.ch/kultur/bnf/rss/8786",
  "srf-health": "https://www.srf.ch/bnf/rss/19919909",
  "srf-sustainability": "https://www.srf.ch/bnf/rss/19920002",
  "srf-humanity": "https://www.srf.ch/bnf/rss/19920107",
  "srf-nature": "https://www.srf.ch/bnf/rss/19920818",
  "srf-knowledge": "https://www.srf.ch/bnf/rss/630",
  "srf-technology": "https://www.srf.ch/bnf/rss/19920122",
  winfuture: "https://static.winfuture.de/feeds/WinFuture-News-rss2.0.xml",
  engadget: "https://www.engadget.com/rss.xml",
  heise: "https://www.heise.de/rss/heise-atom.xml",
  ubergizmo: "https://www.ubergizmo.com/feed/",
}

export function feedProxyPath(feedId: string): string {
  return `/api/rss/${feedId}`
}
